// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlGACfMZqsPJDnzAZkBpwNAreYBOtFVp0',
    appId: '1:754629974823:web:7a855cd41f1912030f2702',
    messagingSenderId: '754629974823',
    projectId: 'promptvault-e62a8',
    authDomain: 'promptvault-e62a8.firebaseapp.com',
    storageBucket: 'promptvault-e62a8.firebasestorage.app',
    measurementId: 'G-TS5D3VB1EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiQ8ZTWcAjxC914l2U8jtyJdrp8r1sTAM',
    appId: '1:754629974823:android:f3f732a49915c5810f2702',
    messagingSenderId: '754629974823',
    projectId: 'promptvault-e62a8',
    storageBucket: 'promptvault-e62a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDfWPWy1bltA5vLfATWxBH-1uuXLa599M',
    appId: '1:754629974823:ios:ac46a3aba7e112ef0f2702',
    messagingSenderId: '754629974823',
    projectId: 'promptvault-e62a8',
    storageBucket: 'promptvault-e62a8.firebasestorage.app',
    iosBundleId: 'com.example.promptVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDfWPWy1bltA5vLfATWxBH-1uuXLa599M',
    appId: '1:754629974823:ios:ac46a3aba7e112ef0f2702',
    messagingSenderId: '754629974823',
    projectId: 'promptvault-e62a8',
    storageBucket: 'promptvault-e62a8.firebasestorage.app',
    iosBundleId: 'com.example.promptVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlGACfMZqsPJDnzAZkBpwNAreYBOtFVp0',
    appId: '1:754629974823:web:321be223fd2749b20f2702',
    messagingSenderId: '754629974823',
    projectId: 'promptvault-e62a8',
    authDomain: 'promptvault-e62a8.firebaseapp.com',
    storageBucket: 'promptvault-e62a8.firebasestorage.app',
    measurementId: 'G-LBT845WXLX',
  );
}